# dbt_project.yml
name: my_dbt_project
version: 1.0.0
config-version: 2

profile: default

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  staging:
    +materialized: view
  marts:
    +materialized: table

# >>> ADD OR UPDATE THIS VARS BLOCK <<<
vars:
  execution_date: '2020-01-01' # <--- Provide a default date for compilation/devs