# dbt_project.yml
name: my_dbt_project
version: 1.0.0
config-version: 2

profile: default  # matches the profile in profiles.yml

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Seeds configuration
seeds: 
  my_dbt_project:
    taxi_zone_lookup:
      +column_types:
        locationid: numeric

