default:  # profile name
  target: dev  # default target
  outputs:
    dev:
      type: clickhouse
      host: clickhouse        # your ClickHouse host (container name or IP)
      port: 8123              # HTTP port for ClickHouse
      user: "ziadashraf98765" # your ClickHouse username
      password: "x5x6x7x8"    # your ClickHouse password
      schema: data_warehouse  # the "database" in ClickHouse