default:  # profile name
  target: dev  # default target
  outputs:
    dev:
      type: clickhouse
      threads: 4
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_HTTP_PORT', '8123') | as_number }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      schema: "{{ env_var('CLICKHOUSE_DB', 'data_warehouse') }}"