version: 2
sources:
- name: raw
  database: ingest_db
  schema: public
  tables:
  - name: green_tripdata_2018-01
  - name: green_tripdata_2018-02
  - name: green_tripdata_2018-03
  - name: green_tripdata_2018-04
  - name: green_tripdata_2018-05
  - name: green_tripdata_2018-06
  - name: green_tripdata_2018-07
  - name: green_tripdata_2018-08
  - name: green_tripdata_2018-09
  - name: green_tripdata_2018-10
  - name: green_tripdata_2018-11
  - name: green_tripdata_2018-12
  - name: green_tripdata_2019-01
  - name: green_tripdata_2019-02
  - name: green_tripdata_2019-03
  - name: green_tripdata_2019-04
  - name: green_tripdata_2019-05
  - name: green_tripdata_2019-06
  - name: green_tripdata_2019-07
  - name: green_tripdata_2019-08
  - name: green_tripdata_2019-09
  - name: green_tripdata_2019-10
  - name: green_tripdata_2019-11
  - name: green_tripdata_2019-12
  - name: green_tripdata_2020-01
  - name: green_tripdata_2020-02
  - name: green_tripdata_2020-03
  - name: green_tripdata_2020-04
  - name: green_tripdata_2020-05
  - name: green_tripdata_2020-06
  - name: green_tripdata_2020-07
  - name: green_tripdata_2020-08
  - name: green_tripdata_2020-09
  - name: green_tripdata_2020-10
  - name: green_tripdata_2020-11
  - name: green_tripdata_2020-12
  - name: green_tripdata_2021-01
  - name: green_tripdata_2021-02
  - name: green_tripdata_2021-03
  - name: green_tripdata_2021-04
  - name: green_tripdata_2021-05
  - name: green_tripdata_2021-06
  - name: green_tripdata_2021-07
  - name: green_tripdata_2021-08
  - name: green_tripdata_2021-09
  - name: green_tripdata_2021-10
  - name: green_tripdata_2021-11
  - name: green_tripdata_2021-12
  - name: green_tripdata_2022-01
  - name: green_tripdata_2022-02
  - name: green_tripdata_2022-03
  - name: green_tripdata_2022-04
  - name: green_tripdata_2022-05
  - name: green_tripdata_2022-06
  - name: green_tripdata_2022-07
  - name: green_tripdata_2022-08
  - name: green_tripdata_2022-09
  - name: green_tripdata_2022-10
  - name: green_tripdata_2022-11
  - name: green_tripdata_2022-12
  - name: green_tripdata_2023-01
  - name: green_tripdata_2023-02
  - name: green_tripdata_2023-03
  - name: green_tripdata_2023-04
  - name: green_tripdata_2023-05
  - name: green_tripdata_2023-06
  - name: green_tripdata_2023-07
  - name: green_tripdata_2023-08
  - name: green_tripdata_2023-09
  - name: green_tripdata_2023-10
  - name: green_tripdata_2023-11
  - name: green_tripdata_2023-12
  - name: green_tripdata_2024-01
  - name: green_tripdata_2024-02
  - name: green_tripdata_2024-03
  - name: green_tripdata_2024-04
  - name: green_tripdata_2024-05
  - name: green_tripdata_2024-06
  - name: green_tripdata_2024-07
  - name: green_tripdata_2024-08
  - name: green_tripdata_2024-09
  - name: green_tripdata_2024-10
  - name: green_tripdata_2024-11
  - name: green_tripdata_2024-12
  - name: green_tripdata_2025-01
  - name: green_tripdata_2025-02
  - name: green_tripdata_2025-03
  - name: green_tripdata_2025-04
  - name: green_tripdata_2025-05
  - name: green_tripdata_2025-06
  - name: green_tripdata_2025-07
  - name: green_tripdata_2025-08
  - name: green_tripdata_2025-09
  - name: green_tripdata_2025-10
  - name: green_tripdata_2025-11
  - name: green_tripdata_2025-12
  - name: green_tripdata_2026-01
  - name: green_tripdata_2026-02
  - name: green_tripdata_2026-03
  - name: green_tripdata_2026-04
  - name: green_tripdata_2026-05
  - name: green_tripdata_2026-06
  - name: green_tripdata_2026-07
  - name: green_tripdata_2026-08
  - name: green_tripdata_2026-09
  - name: green_tripdata_2026-10
  - name: green_tripdata_2026-11
  - name: green_tripdata_2026-12
  - name: green_tripdata_2027-01
  - name: green_tripdata_2027-02
  - name: green_tripdata_2027-03
  - name: green_tripdata_2027-04
  - name: green_tripdata_2027-05
  - name: green_tripdata_2027-06
  - name: green_tripdata_2027-07
  - name: green_tripdata_2027-08
  - name: green_tripdata_2027-09
  - name: green_tripdata_2027-10
  - name: green_tripdata_2027-11
  - name: green_tripdata_2027-12
