services:
  # PostgreSQL Database for Airflow
  postgres_airflow:
    image: postgres:16
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_airflow:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    mem_limit: 2g
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "ziadashraf98765"
      MINIO_ROOT_PASSWORD: "x5x6x7x8"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_storage:/data


  clickhouse:
    image: clickhouse/clickhouse-server:24.3.8
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9005:9000"
    environment:
      CLICKHOUSE_USER: 'ziadashraf98765'
      CLICKHOUSE_PASSWORD: 'x5x6x7x8'
      CLICKHOUSE_DB: 'data_warehouse'
    volumes:
      - clickhouse_data_warehouse:/var/lib/clickhouse

  # Metabase for data visualization
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: airflow
      MB_DB_PORT: 5432
      MB_DB_USER: airflow
      MB_DB_PASS: airflow
      MB_DB_HOST: postgres
    volumes:
      - metabase_data:/metabase-data

  # Airflow Initialization Service
  airflow-init:
    build:       
      context: .
      dockerfile: airflow/docker/Dockerfile
    depends_on:
      - postgres_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: '3012001'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: utc
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: True
      AIRFLOW__SMTP__SMTP_SSL: False
      AIRFLOW__SMTP__SMTP_USER: ziadashraf98765@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: bqdv sxlf txat hfqs
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ziadashraf98765@gmail.com
    entrypoint: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email ziadashraf98765@gmail.com
      "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/src/ingestion:/opt/airflow/src/ingestion
      - ./airflow/airflow_logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

  # Airflow Webserver
  airflow-webserver:
    build:       
      context: .
      dockerfile: airflow/docker/Dockerfile
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres_airflow
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: '3012001'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: utc
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__SESSION_BACKEND: securecookie
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: True
      AIRFLOW__SMTP__SMTP_SSL: False
      AIRFLOW__SMTP__SMTP_USER: ziadashraf98765@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: bqdv sxlf txat hfqs
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ziadashraf98765@gmail.com
      PYTHONPATH: /opt/airflow/src:/opt/airflow/src
    command: webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/src/ingestion:/opt/airflow/src/ingestion 
      - ./airflow/airflow_logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock

  # Airflow Scheduler
  airflow-scheduler:
    build: 
      context: .
      dockerfile: airflow/docker/Dockerfile
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: '3012001'
      AIRFLOW__CORE__DEFAULT_TIMEZONE: utc
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False' 
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: True
      AIRFLOW__SMTP__SMTP_SSL: False
      AIRFLOW__SMTP__SMTP_USER: ziadashraf98765@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: bqdv sxlf txat hfqs
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ziadashraf98765@gmail.com
      PYTHONPATH: /opt/airflow/src:/opt/airflow/src
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/src/ingestion:/opt/airflow/src/ingestion
      - ./airflow/airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock


  # dbt (Data Build Tool
  dbt:
    build:
      context: .
      dockerfile: dbt/docker/Dockerfile
    container_name: dbt
    volumes:
      - ./dbt:/dbt
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
    working_dir: /dbt
    entrypoint: /bin/bash  # Override the default entrypoint
    command: -c "tail -f /dev/null"  # Keep the container running



# Named Volumes
volumes:
  postgres_airflow:
  metabase_data:
  clickhouse_data_warehouse:
  minio_storage:
