"""Forecast schemas for historical comparisons and model predictions."""
from pydantic import BaseModel, Field


class HistoricalPoint(BaseModel):
    """Historical demand point for a specific zone and service type."""
    datetime: str = Field(..., description="Timestamp in ISO or YYYY-MM-DD HH:MM:SS format")
    total_trips: float = Field(..., description="Historical observed trip count")


class ForecastPoint(BaseModel):
    """Predicted demand point generated by ONNX inference model."""
    datetime: str = Field(..., description="Forecasted timestamp in ISO or YYYY-MM-DD HH:MM:SS format")
    predicted_trips: float = Field(..., description="Predicted taxi trip demand")
    model_version: str = Field(..., description="Version of model producing the inference")
